### ISSUE TITLE
How to garbage collect Shared Buffer memory?

### ISSUE THREAD

**Issue by steelbrain** [voodooattack/shared-buffer#2]
Forgive my ignorance but in the docs I only see API to create/get shared buffer but nothing to see how to destroy them after use.

How would one free the memory these shared buffers hold?

**Comment by voodooattack** [comment]
Fixed with version 1.2.0, which introduces `detachSharedBuffer(...)` as well as an automatic detaching mechanism.

Thanks for bringing this to my attention, and my sincerest apologies for the long response time.
